/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void listToJSON() {

        TaskList list = new TaskList();
        list.add("hamza");
        assertEquals("""
                [
                {
                    "id": 0,
                    "body": hamza,
                    "status": TODO,
                    "last updated": -
                }
                ]""",list.toJSON());
    }
    @Test void taskToJSON() {
        Task t = new Task("hamza", 1);
        assertEquals("""
                {
                    "id": 1,
                    "body": hamza,
                    "status": TODO,
                    "last updated": -
                }
                """, t.toJSON());
    }
    @Test void addCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        list1.add("hama");
        assertNotEquals(list1,list2);
    }
    @Test void updateCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        list1.add("hamza");
        list2.add("hamza");
        assertEquals(list1,list2);
        list1.updateStatus(,TaskStatus.DONE);
        assertNotEquals(list1,list2);
    }
    @Test void removeCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        TaskList list3 = new TaskList();
        list1.add("hamza");
        list2.add("hamza");
        list3.add("hamza");
        list3.add("yassen");
        list3.add("maharmeh");
        list1.remove(new String[]{"0"});
        list3.remove(new String[]{"2","1"});
        assertEquals(list3,list2);
        assertNotEquals(list1,list2);
    }
}