/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void listToJSON() {

        TaskList list = new TaskList();
        list.add("hamza");
        String date = LocalDate.now().toString();
        String format   = """
                [
                    {
                        "id": 0,
                        "body": hamza,
                        "status": TODO,
                        "created at": %s,
                        "last updated": -
                    }
                ]""";

        assertEquals(String.format(format,date),list.toJSON());
    }
    @Test void taskToJSON() {
        Task t = new Task("hamza", 1);
        String date = LocalDate.now().toString();
        String fomat = """
                    {
                        "id": 1,
                        "body": hamza,
                        "status": TODO,
                        "created at": %s,
                        "last updated": -
                    }
                """;
        assertEquals(String.format(fomat,date), t.toJSON());
    }
    @Test void addCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        list1.add("hama");
        assertNotEquals(list1,list2);
    }
    @Test void updateCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        list1.add("test");
        list2.add("test");
        assertEquals(list1,list2);
        list1.updateStatus(TaskStatus.DONE,new String[] {"0"});
        assertNotEquals(list1,list2);
    }
    @Test void removeCommand() {
        TaskList list1 = new TaskList();
        TaskList list2 = new TaskList();
        TaskList list3 = new TaskList();
        list1.add("hamza");
        list2.add("hamza");
        list3.add("hamza");
        list3.add("yassen");
        list3.add("maharmeh");
        list1.remove(new String[]{"0"});
        list3.remove(new String[]{"2","1"});
        assertEquals(list3,list2);
        assertNotEquals(list1,list2);
    }
}